Repository chingu-voyages/v8-chimeras-team-02, pull requests merged in 2019-04, with the labels that each got.

#34 Implement getQuestions query in Home and GiveAnswer
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/screens/GiveAnswer.js
  frontend/src/screens/Home.js
Labels: enhancement

#35 Rubens fix mutation branch
  backend/package-lock.json
  backend/src/connectors/index.js
Labels: bug

#52 GiveAnswer mutations
  frontend/package-lock.json
  frontend/src/screens/GiveAnswer.js
  frontend/src/screens/Home.js
  frontend/src/screens/NewQuestion.js
Labels: enhancement

#59 Update onChange and fix typos | closes #49
  frontend/src/components/Header.js
  frontend/src/screens/LogIn.js
  frontend/src/screens/NewQuestion.js
Labels: bug, enhancement

#94 Refetch query in 'Home.js'
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/components/Answer.js
  frontend/src/components/CompleteItem.js
  frontend/src/screens/NewQuestion.js
Labels: bug
